PG_MAJOR ?= 18

ifeq ($(PG_MAJOR),18)
PG_VERSION ?= 18.4
PERCONA_RELEASE ?= 2
PGTDE_VERSION ?= 2.2.1
POSTGIS_VERSION ?= 3.5.7
PGVECTOR_VERSION ?= 0.8.3
WAL2JSON_VERSION ?= 2.6
PGREPACK_VERSION ?= 1.5.3
PGAUDIT_VERSION ?= 18.0
SET_USER_VERSION ?= 4.2.0
PG_STAT_MONITOR_VERSION ?= 2.3.2
PG_GATHER_VERSION ?= 33
else
$(error pgtde supports PG_MAJOR=18 for now)
endif

PKG_REV ?= 2PIGSTY
PACKAGE ?= pgtde-$(PG_MAJOR)
CORE_TARBALL := percona-postgresql-$(PG_VERSION).tar.gz
TDE_TARBALL := percona-pg_tde$(PG_MAJOR)-$(PGTDE_VERSION).tar.gz
PG_CONFIG_WRAPPER := pgtde-pg-config
SFCGAL_CONFIG_WRAPPER := pgtde-sfcgal-config
POSTGIS_TARBALL := percona-postgis-$(POSTGIS_VERSION).tar.gz
PGVECTOR_TARBALL := percona-pgvector_$(PG_MAJOR)-$(PGVECTOR_VERSION).tar.gz
WAL2JSON_TARBALL := percona-wal2json-$(WAL2JSON_VERSION).tar.gz
PGREPACK_TARBALL := percona-pg_repack-$(PGREPACK_VERSION).tar.gz
PGAUDIT_TARBALL := percona-pgaudit-$(PGAUDIT_VERSION).tar.gz
SET_USER_TARBALL := percona-pgaudit$(PG_MAJOR)_set_user-$(SET_USER_VERSION).tar.gz
PG_STAT_MONITOR_TARBALL := percona-pg-stat-monitor$(PG_MAJOR)-$(PG_STAT_MONITOR_VERSION).tar.gz
PG_GATHER_TARBALL := percona-pg_gather-$(PG_GATHER_VERSION).tar.gz

SOURCE_DIR ?= ../SOURCES
CORE_SOURCE ?= $(SOURCE_DIR)/$(CORE_TARBALL)
TDE_SOURCE ?= $(SOURCE_DIR)/$(TDE_TARBALL)
PG_CONFIG_SOURCE ?= $(SOURCE_DIR)/$(PG_CONFIG_WRAPPER)
SFCGAL_CONFIG_SOURCE ?= $(SOURCE_DIR)/$(SFCGAL_CONFIG_WRAPPER)
POSTGIS_SOURCE ?= $(SOURCE_DIR)/$(POSTGIS_TARBALL)
PGVECTOR_SOURCE ?= $(SOURCE_DIR)/$(PGVECTOR_TARBALL)
WAL2JSON_SOURCE ?= $(SOURCE_DIR)/$(WAL2JSON_TARBALL)
PGREPACK_SOURCE ?= $(SOURCE_DIR)/$(PGREPACK_TARBALL)
PGAUDIT_SOURCE ?= $(SOURCE_DIR)/$(PGAUDIT_TARBALL)
SET_USER_SOURCE ?= $(SOURCE_DIR)/$(SET_USER_TARBALL)
PG_STAT_MONITOR_SOURCE ?= $(SOURCE_DIR)/$(PG_STAT_MONITOR_TARBALL)
PG_GATHER_SOURCE ?= $(SOURCE_DIR)/$(PG_GATHER_TARBALL)
PKG_OUTPUT_DIR ?= $(HOME)/ext/pkg
