#==============================================================#
# File      :   Makefile
# Desc      :   pgsty/deb repo shortcuts
# Ctime     :   2024-07-28
# Mtime     :   2026-01-17
# Path      :   Makefile
# Author    :   Ruohang Feng (rh@vonng.com)
# License   :   Apache-2.0
#==============================================================#

default:
	@echo "pig build pkg <xxx> or make <xxx> to build extensions"

###############################################################
#                     Rust Extensions                        #
###############################################################

timescaledb_toolkit:
	cd timescaledb_toolkit && make

pg_later:
	cd pg_later && make

pg_polyline:
	cd pg_polyline && make

pg_tzf:
	cd pg_tzf && make

vchord:
	cd vchord && make

pgvectorscale:
	cd pgvectorscale && make

pg_vectorize:
	cd pg_vectorize && make

pg_summarize:
	cd pg_summarize && make

pg_tiktoken:
	cd pg_tiktoken && make

pgml:
	cd pgml && make

pg_search:
	cd pg_search && make

pg_bestmatch:
	cd pg_bestmatch && make

vchord_bm25:
	cd vchord_bm25 && make

pg_tokenizer:
	cd pg_tokenizer && make

pg_mooncake:
	cd pg_mooncake && make

pg_parquet:
	cd pg_parquet && make

pg_graphql:
	cd pg_graphql && make

pg_jsonschema:
	cd pg_jsonschema && make

pg_cardano:
	cd pg_cardano && make

plprql:
	cd plprql && make

pglite_fusion:
	cd pglite_fusion && make

pg_smtp_client:
	cd pg_smtp_client && make

pg_render:
	cd pg_render && make

pg_idkit:
	cd pg_idkit && make

pgx_ulid:
	cd pgx_ulid && make

pg_base58:
	cd pg_base58 && make

pg_convert:
	cd pg_convert && make

pgdd:
	cd pgdd && make

pg_explain_ui:
	cd pg_explain_ui && make

pg_session_jwt:
	cd pg_session_jwt && make

pg_anon:
	cd pg_anon && make

pgsmcrypto:
	cd pgsmcrypto && make

wrappers:
	cd wrappers && make
pglinter:
	cd pglinter && make
pg_enigma:
	cd pg_enigma && make
pg_typeid:
	cd pg_typeid && make



###############################################################
#            Category: TIME - Time & Schedule                #
###############################################################

timescaledb:
	cd timescaledb && make

pg_timeseries:
	cd pg_timeseries && make

temporal_tables:
	cd temporal_tables && make

emaj:
	cd emaj && make

table_version:
	cd table_version && make

pg_task:
	cd pg_task && make

pg_background:
	cd pg_background && make

pg_partman: # PGDG Included
	cd pg_partman && make



###############################################################
#            Category: GIS  - Geospatial                     #
###############################################################

geoip:
	cd geoip && make

pg_geohash:
	cd pg_geohash && make


###############################################################
#            Category: RAG  - RAG & Vector                   #
###############################################################

smlar:
	cd smlar && make

pg4ml:
	cd pg4ml && make


###############################################################
#            Category: FTS  - Full-Text Search               #
###############################################################
hunspell:
	cd hunspell && make

pgroonga:
	cd pgroonga && make

pg_bigm:
	cd pg_bigm && make

pg_biscuit:
	cd pg_biscuit && make

pg_textsearch:
	cd pg_textsearch && make

scws:
	cd scws && make
zhparser:
	cd zhparser && make


###############################################################
#            Category: OLAP - OLAP & Analytics               #
###############################################################

citus:
	cd citus && make

hydra:
	cd hydra && make

pg_duckdb:
	cd pg_duckdb && make

duckdb_fdw:
	cd duckdb_fdw && make

pg_fkpart:
	cd pg_fkpart && make

pg_clickhouse:
	cd pg_clickhouse && make


###############################################################
#            Category: FEAT - Functionality                  #
###############################################################
age: # PGDG Included
	cd age && make

pg_ttl_index:
	cd pg_ttl_index && make

index_advisor:
	cd index_advisor && make

pg_plan_filter:
	cd pg_plan_filter && make

imgsmlr:
	cd imgsmlr && make

pg_ivm:
	cd pg_ivm && make

pg_incremental:
	cd pg_incremental && make

pgmq:
	cd pgmq && make

omnigres:
	cd omnigres && make

pg_ai_query:
	cd pg_ai_query && make


###############################################################
#            Category: LANG - Languages                      #
###############################################################
plxslt:
	cd plxslt && make

pg_tle:
	cd pg_tle && make

plv8:
	cd plv8 && make

pljs: # PGDG Included
	cd pljs && make

###############################################################
#            Category: TYPE - Data Types                     #
###############################################################

pgpdf:
	cd pgpdf && make

md5hash:
	cd md5hash && make

pg_country:
	cd pg_country && make

pg_xenophile:
	cd pg_xenophile && make

pg_currency:
	cd pg_currency && make

pgcollection:
	cd pgcollection && make

pguint:
	cd pguint && make

pg_uint128:
	cd pg_uint128 && make

hashtypes:
	cd hashtypes && make

pg_duration:
	cd pg_duration && make

pg_uri:
	cd pg_uri && make

pg_emailaddr:
	cd pg_emailaddr && make

pg_acl:
	cd pg_acl && make

timestamp9:
	cd timestamp9 && make

chkpass:
	cd chkpass && make


###############################################################
#            Category: UTIL - Utilities                      #
###############################################################

pg_gzip:
	cd pg_gzip && make

pg_bzip:
	cd pg_bzip && make

pg_zstd:
	cd pg_zstd && make

pg_net:
	cd pg_net && make

pg_curl:
	cd pg_curl && make

pgjq:
	cd pgjq && make

pg_retry:
	cd pg_retry && make

pgjwt:
	cd pgjwt && make

pg_html5_email_address:
	cd pg_html5_email_address && make

url_encode:
	cd url_encode && make

pgsql_tweaks:
	cd pgsql_tweaks && make

pg_extra_time:
	cd pg_extra_time && make

pgqr:
	cd pgqr && make

pg_protobuf:
	cd pg_protobuf && make

pg_envvar:
	cd pg_envvar && make

floatfile:
	cd floatfile && make

pg_readme:
	cd pg_readme && make

ddl_historization:
	cd ddl_historization && make

data_historization:
	cd data_historization && make

pg_schedoc:
	cd pg_schedoc && make

pg_hashlib:
	cd pg_hashlib && make

pg_xxhash:
	cd pg_xxhash && make

shacrypt:
	cd shacrypt && make

cryptint:
	cd cryptint && make

pg_ecdsa:
	cd pg_ecdsa && make

pgsparql:
	cd pgsparql && make




###############################################################
#            Category: FUNC - Functions                      #
###############################################################

pg_uuidv7:
	cd pg_uuidv7 && make

permuteseq:
	cd permuteseq && make

pg_hashids:
	cd pg_hashids && make

sequential_uuids:
	cd sequential_uuids && make

topn:
	cd topn && make

quantile:
	cd quantile && make

lower_quantile:
	cd lower_quantile && make

count_distinct:
	cd count_distinct && make

omnisketch:
	cd omnisketch && make

ddsketch:
	cd ddsketch && make

vasco:
	cd vasco && make

pgxicor:
	cd pgxicor && make

pg_weighted_statistics:
	cd pg_weighted_statistics && make

floatvec:
	cd floatvec && make

aggs_for_vecs:
	cd aggs_for_vecs && make

aggs_for_arrays:
	cd aggs_for_arrays && make

pg_arraymath:
	cd pg_arraymath && make
pg_csv:
	cd pg_csv && make
pg_math:
	cd pg_math && make

pg_random:
	cd pg_random && make

pg_base36:
	cd pg_base36 && make

pg_base62:
	cd pg_base62 && make

pg_financial:
	cd pg_financial && make


###############################################################
#            Category: ADMIN - Administration                 #
###############################################################

pg_rewrite:
	cd pg_rewrite && make

pg_cooldown:
	cd pg_cooldown && make

pg_ddlx:
	cd pg_ddlx && make

pg_readonly:
	cd pg_readonly && make

pg_permissions:
	cd pg_permissions && make

pg_upless:
	cd pg_upless && make

pgcozy:
	cd pgcozy && make

pg_orphaned:
	cd pg_orphaned && make

pg_crash:
	cd pg_crash && make

pg_cheat_funcs:
	cd pg_cheat_funcs && make

pg_fio:
	cd pg_fio && make

pg_savior:
	cd pg_savior && make

safeupdate:
	cd safeupdate && make

pg_drop_events:
	cd pg_drop_events && make


###############################################################
#            Category: STAT - Statistics                     #
###############################################################

pg_profile:
	cd pg_profile && make

pg_tracing:
	cd pg_tracing && make

pg_stat_monitor:
	cd pg_stat_monitor && make

pg_store_plans:
	cd pg_store_plans && make

pgsentinel: # PGDG Included
	cd pgsentinel && make

pgfincore: # PGDG Included
	cd pgfincore && make

system_stats:
	cd system_stats && make

pg_meta:
	cd pg_meta && make

pgnodemx:
	cd pgnodemx && make

pg_sqlog:
	cd pg_sqlog && make

pgmeminfo:
	cd pgmeminfo && make

pg_relusage:
	cd pg_relusage && make

pagevis:
	cd pagevis && make


###############################################################
#            Category: SEC  - Security                       #
###############################################################

passwordcheck_cracklib:
	cd passwordcheck_cracklib && make

supautils:
	cd supautils && make

pgsodium:
	cd pgsodium && make

pg_vault:
	cd pg_vault && make

pg_tde:
	cd pg_tde && make

pg_auth_mon:
	cd pg_auth_mon && make

pgcryptokey:
	cd pgcryptokey && make

pg_jobmon:
	cd pg_jobmon && make

logerrors:
	cd logerrors && make

login_hook:
	cd login_hook && make

pg_auditor:
	cd pg_auditor && make

sslutils:
	cd sslutils && make

pg_noset:
	cd pg_noset && make


###############################################################
#            Category: FDW  - FDW                            #
###############################################################

pgspider_ext:
	cd pgspider_ext && make

sqlite_fdw:
	cd sqlite_fdw && make

redis_fdw:
	cd redis_fdw && make

pg_redis_pubsub:
	cd pg_redis_pubsub && make

kafka_fdw:
	cd kafka_fdw && make

libfq:
	cd libfq && make
firebird_fdw:
	cd firebird_fdw && make

aws_s3:
	cd aws_s3 && make

log_fdw:
	cd log_fdw && make

etcd_fdw:
	cd etcd_fdw && make


###############################################################
#            Category: SIM  - Similarity                     #
###############################################################

documentdb:
	cd documentdb && make

pgtt:
	cd pgtt && make

session_variable:
	cd session_variable && make

pg_statement_rollback:
	cd pg_statement_rollback && make

spat:
	cd spat && make


###############################################################
#            Category: ETL  - ETL                            #
###############################################################

pglogical_ticker:
	cd pglogical_ticker && make

pg_failover_slots:
	cd pg_failover_slots && make

db_migrator:
	cd db_migrator && make

pgactive:
	cd pgactive && make

wal2mongo:
	cd wal2mongo && make

decoder_raw:
	cd decoder_raw && make

pg_bulkload:
	cd pg_bulkload && make



###############################################################
#                          Kernel                             #
###############################################################
openhalodb:
	cd openhalodb && make
oriolepg_17:
	cd orioledb-17 && make
orioledb:
	cd orioledb && make


###############################################################
#                        1. Building                          #
###############################################################
# noext install
deps:
	sudo dpkg -i ~/libduckdb_*.deb
	sudo dpkg -i ~/libfq_*.deb
	sudo dpkg -i ~/scws_*.deb

collect:
	mkdir -p /tmp/deb
	cp -r ~/*.deb /tmp/deb/


.PHONY: deps collect \
	timescaledb_toolkit pg_later pg_polyline pg_tzf vchord pgvectorscale pg_vectorize pg_summarize pg_tiktoken pgml pg_search pg_bestmatch vchord_bm25 pg_tokenizer pg_mooncake pg_parquet pg_graphql pg_jsonschema pg_cardano plprql pglite_fusion pg_smtp_client pg_render pg_idkit pgx_ulid pg_base58 pg_convert pgdd pg_explain_ui pg_session_jwt pg_anon pgsmcrypto wrappers \
	timescaledb pg_timeseries temporal_tables emaj table_version pg_task pg_background pg_partman \
	geoip pg_geohash \
	smlar pg4ml \
	hunspell pgroonga pg_bigm pg_biscuit scws zhparser pg_textsearch \
	citus hydra pg_duckdb duckdb_fdw pg_fkpart pg_clickhouse \
	age pg_ttl_index index_advisor pg_plan_filter imgsmlr pg_ivm pg_incremental pgmq omnigres pg_ai_query \
	plxslt pg_tle plv8 pljs \
	pgpdf md5hash pg_country pg_xenophile pg_currency pgcollection pguint pg_uint128 hashtypes pg_duration pg_uri pg_emailaddr pg_acl timestamp9 chkpass \
	pg_gzip pg_bzip pg_zstd pg_net pg_curl pgjq pg_retry pgjwt pg_html5_email_address url_encode pgsql_tweaks pg_extra_time pgqr pg_protobuf pg_envvar floatfile pg_readme ddl_historization data_historization pg_schedoc pg_hashlib pg_xxhash shacrypt cryptint pg_ecdsa pgsparql \
	pg_uuidv7 permuteseq pg_hashids sequential_uuids topn quantile lower_quantile count_distinct omnisketch ddsketch vasco pgxicor pg_weighted_statistics floatvec aggs_for_vecs aggs_for_arrays pg_csv pg_arraymath pg_math pg_random pg_base36 pg_base62 pg_financial \
	pg_rewrite pg_cooldown pg_ddlx pg_readonly pg_permissions pg_upless pgcozy pg_orphaned pg_crash pg_cheat_funcs pg_fio pg_savior safeupdate pg_drop_events \
	pg_profile pg_tracing pg_stat_monitor pg_store_plans pgsentinel pgfincore system_stats pg_meta pgnodemx pg_sqlog pgmeminfo pg_relusage pagevis \
	passwordcheck_cracklib supautils pgsodium pg_vault pg_tde pg_auth_mon pgcryptokey pg_jobmon logerrors login_hook pg_auditor sslutils pg_noset \
	pgspider_ext sqlite_fdw pg_redis_pubsub kafka_fdw libfq firebird_fdw aws_s3 log_fdw etcd_fdw \
	documentdb pgtt session_variable pg_statement_rollback spat \
	pg_failover_slots db_migrator pgactive wal2mongo decoder_raw pg_bulkload \
	pglinter pg_enigma pg_typeid \
	openhalodb oriolepg_17 orioledb
