#==============================================================#
# File      :   Makefile
# Desc      :   pgsty/deb repo shortcuts
# Ctime     :   2024-07-28
# Mtime     :   2026-07-21
# Path      :   Makefile
# Author    :   Ruohang Feng (rh@vonng.com)
# License   :   Apache-2.0
#==============================================================#

default:
	@echo "pig build pkg <xxx> or make <xxx> to build extensions"

###############################################################
#                     Rust Extensions                        #
###############################################################

block_copy_command:
	cd block_copy_command && make

timescaledb_toolkit:
	cd timescaledb_toolkit && make

pg_later:
	cd pg_later && make

pg_polyline:
	cd pg_polyline && make

pg_tzf:
	cd pg_tzf && make

vchord:
	cd vchord && make

pgvectorscale:
	cd pgvectorscale && make

pgvector:
	cd pgvector && make

pg_vectorize:
	cd pg_vectorize && make

pg_summarize:
	cd pg_summarize && make

pg_tiktoken:
	cd pg_tiktoken && make

pg_tiktoken_c:
	cd pg_tiktoken_c && make

pgml:
	cd pgml && make

pg_search:
	cd pg_search && make

pg_when:
	cd pg_when && make

pg_bestmatch:
	cd pg_bestmatch && make

vchord_bm25:
	cd vchord_bm25 && make

pg_tokenizer:
	cd pg_tokenizer && make

pg_mooncake:
	cd pg_mooncake && make

pg_parquet:
	cd pg_parquet && make

pg_graphql:
	cd pg_graphql && make

pg_jsonschema:
	cd pg_jsonschema && make

pg_kazsearch:
	cd pg_kazsearch && make

pg_typescript:
	cd pg_typescript && make

pg_cardano:
	cd pg_cardano && make

pg_rrf:
	cd pg_rrf && make

plprql:
	cd plprql && make

pglite_fusion:
	cd pglite_fusion && make

pg_smtp_client:
	cd pg_smtp_client && make

pgmqtt:
	cd pgmqtt && make

pg_render:
	cd pg_render && make

pg_idkit:
	cd pg_idkit && make

pgx_ulid:
	cd pgx_ulid && make

pg_base58:
	cd pg_base58 && make

pg_convert:
	cd pg_convert && make

pgdd:
	cd pgdd && make

pg_explain_ui:
	cd pg_explain_ui && make

pg_session_jwt:
	cd pg_session_jwt && make

pg_oidc_validator_rust:
	cd pg_oidc_validator_rust && make

pg_oidc_validator:
	cd pg_oidc_validator && make

pg_anon:
	cd pg_anon && make

pgsmcrypto:
	cd pgsmcrypto && make

wrappers:
	cd wrappers && make
pglinter:
	cd pglinter && make
pg_enigma:
	cd pg_enigma && make
pg_typeid:
	cd pg_typeid && make

pg_pinyin:
	cd pg_pinyin && make

pg_eviltransform:
	cd pg_eviltransform && make

pggraph:
	cd pggraph && make

pgrdf:
	cd pgrdf && make

jsonschema:
	cd jsonschema && make



###############################################################
#            Category: TIME - Time & Schedule                #
###############################################################

timescaledb:
	cd timescaledb && make

pg_timeseries:
	cd pg_timeseries && make

pg_bikram_sambat:
	cd pg_bikram_sambat && make

cron_utils:
	cd cron_utils && make

temporal_tables:
	cd temporal_tables && make

emaj:
	cd emaj && make

table_version:
	cd table_version && make

pg_task:
	cd pg_task && make

pg_background:
	cd pg_background && make

inchi:
	cd inchi && make

pg_partman: # PGDG Included
	cd pg_partman && make



###############################################################
#            Category: GIS  - Geospatial                     #
###############################################################

geoip:
	cd geoip && make

pg_geohash:
	cd pg_geohash && make

pghydro:
	cd pghydro && make


###############################################################
#            Category: RAG  - RAG & Vector                   #
###############################################################

smlar:
	cd smlar && make

pg4ml:
	cd pg4ml && make

rdkit:
	cd rdkit && make


###############################################################
#            Category: FTS  - Full-Text Search               #
###############################################################
hunspell:
	cd hunspell && make

pgroonga:
	cd pgroonga && make

pg_bigm:
	cd pg_bigm && make

pg_biscuit:
	cd pg_biscuit && make

pg_textsearch:
	cd pg_textsearch && make

pg_fts:
	cd pg_fts && make

scws:
	cd scws && make
zhparser:
	cd zhparser && make

pg_cjk_parser:
	cd pg_cjk_parser && make

pg_jieba:
	cd pg_jieba && make


###############################################################
#            Category: OLAP - OLAP & Analytics               #
###############################################################

citus:
	cd citus && make

hydra:
	cd hydra && make

storage_engine:
	cd storage_engine && make

datasketches:
	cd datasketches && make

pg_duckdb:
	cd pg_duckdb && make

pg_ducklake:
	cd pg_ducklake && make

pg_lake:
	cd pg_lake && make

duckdb_fdw:
	cd duckdb_fdw && make

pg_fkpart:
	cd pg_fkpart && make

pg_kpart:
	cd pg_kpart && make

pg_clickhouse:
	cd pg_clickhouse && make

pg_orca:
	cd pg_orca && make

###############################################################
#            Category: FDW  - Foreign Data Wrappers          #
###############################################################
multicorn:
	cd multicorn && make


###############################################################
#            Category: FEAT - Functionality                  #
###############################################################
age: # PGDG Included
	cd age && make

pg_ttl_index:
	cd pg_ttl_index && make

index_advisor:
	cd index_advisor && make

pg_plan_filter:
	cd pg_plan_filter && make

imgsmlr:
	cd imgsmlr && make

pg_ivm:
	cd pg_ivm && make

provsql:
	cd provsql && make

pg_durable:
	cd pg_durable && make

pgmnemo:
	cd pgmnemo && make

pg_projection:
	cd pg_projection && make

pg_stl:
	cd pg_stl && make

pg_sorted_heap:
	cd pg_sorted_heap && make

pg_incremental:
	cd pg_incremental && make

pgmq:
	cd pgmq && make

pgmb:
	cd pgmb && make

omnigres:
	cd omnigres && make

pg_ai_query:
	cd pg_ai_query && make


###############################################################
#            Category: LANG - Languages                      #
###############################################################
plxslt:
	cd plxslt && make

pg_tle:
	cd pg_tle && make

plv8:
	cd plv8 && make

pljs: # PGDG Included
	cd pljs && make

plx:
	cd plx && make

###############################################################
#            Category: TYPE - Data Types                     #
###############################################################

pgpdf:
	cd pgpdf && make

md5hash:
	cd md5hash && make

pg_country:
	cd pg_country && make

pg_xenophile:
	cd pg_xenophile && make

pg_currency:
	cd pg_currency && make

pgcollection:
	cd pgcollection && make

pguint:
	cd pguint && make

pg_uint128:
	cd pg_uint128 && make

pg_roaringbitmap:
	cd pg_roaringbitmap && make

pg_unit:
	cd pg_unit && make

pg_text_semver:
	cd pg_text_semver && make

hashtypes:
	cd hashtypes && make

pg_duration:
	cd pg_duration && make

pg_uri:
	cd pg_uri && make

pg_emailaddr:
	cd pg_emailaddr && make

pg_acl:
	cd pg_acl && make

timestamp9:
	cd timestamp9 && make

chkpass:
	cd chkpass && make


###############################################################
#            Category: UTIL - Utilities                      #
###############################################################

pg_gzip:
	cd pg_gzip && make

pg_http:
	cd pg_http && make

pg_bzip:
	cd pg_bzip && make

pg_zstd:
	cd pg_zstd && make

pg_net:
	cd pg_net && make

pg_curl:
	cd pg_curl && make

pgjq:
	cd pgjq && make

pg_retry:
	cd pg_retry && make

pgjwt:
	cd pgjwt && make

pg_html5_email_address:
	cd pg_html5_email_address && make

pg_utl_smtp:
	cd pg_utl_smtp && make

url_encode:
	cd url_encode && make

pgsql_tweaks:
	cd pgsql_tweaks && make

pg_extra_time:
	cd pg_extra_time && make

pgqr:
	cd pgqr && make

pg_protobuf:
	cd pg_protobuf && make

pg_envvar:
	cd pg_envvar && make

floatfile:
	cd floatfile && make

external_file:
	cd external_file && make

pg_byteamagic:
	cd pg_byteamagic && make

pg_readme:
	cd pg_readme && make

ddl_historization:
	cd ddl_historization && make

data_historization:
	cd data_historization && make

pg_schedoc:
	cd pg_schedoc && make

pg_hashlib:
	cd pg_hashlib && make

pg_xxhash:
	cd pg_xxhash && make

shacrypt:
	cd shacrypt && make

cryptint:
	cd cryptint && make

pg_ecdsa:
	cd pg_ecdsa && make

pgsparql:
	cd pgsparql && make




###############################################################
#            Category: FUNC - Functions                      #
###############################################################

pg_uuidv7:
	cd pg_uuidv7 && make

pg_uuid_v8:
	cd pg_uuid_v8 && make

permuteseq:
	cd permuteseq && make

pg_hashids:
	cd pg_hashids && make

sequential_uuids:
	cd sequential_uuids && make

topn:
	cd topn && make

quantile:
	cd quantile && make

lower_quantile:
	cd lower_quantile && make

count_distinct:
	cd count_distinct && make

omnisketch:
	cd omnisketch && make

ddsketch:
	cd ddsketch && make

vasco:
	cd vasco && make

pgxicor:
	cd pgxicor && make

pg_weighted_statistics:
	cd pg_weighted_statistics && make

floatvec:
	cd floatvec && make

aggs_for_vecs:
	cd aggs_for_vecs && make

aggs_for_arrays:
	cd aggs_for_arrays && make

parray_gin:
	cd parray_gin && make

pg_accumulator:
	cd pg_accumulator && make

pg_arraymath:
	cd pg_arraymath && make
# pg_csv 1.0.2 and later are provided by PGDG.
pg_math:
	cd pg_math && make

pg_random:
	cd pg_random && make

pg_base36:
	cd pg_base36 && make

pg_base62:
	cd pg_base62 && make

pg_financial:
	cd pg_financial && make

argm:
	cd argm && make

faker:
	cd faker && make

dbt2:
	cd dbt2 && make


###############################################################
#            Category: ADMIN - Administration                 #
###############################################################

pg_rewrite:
	cd pg_rewrite && make

pg_query_rewrite:
	cd pg_query_rewrite && make

pgdisablelogerror:
	cd pgdisablelogerror && make

pg_cooldown:
	cd pg_cooldown && make

pg_ddlx:
	cd pg_ddlx && make

pg_readonly:
	cd pg_readonly && make

pg_permissions:
	cd pg_permissions && make

pg_upless:
	cd pg_upless && make

pgcozy:
	cd pgcozy && make

pg_orphaned:
	cd pg_orphaned && make

pg_crash:
	cd pg_crash && make

pg_cheat_funcs:
	cd pg_cheat_funcs && make

pg_fio:
	cd pg_fio && make

pg_qos:
	cd pg_qos && make

pg_savior:
	cd pg_savior && make

safeupdate:
	cd safeupdate && make

pg_drop_events:
	cd pg_drop_events && make

pg_dbms_lock:
	cd pg_dbms_lock && make

pg_dbms_errlog:
	cd pg_dbms_errlog && make

pg_dbms_metadata:
	cd pg_dbms_metadata && make

pg_dbms_job:
	cd pg_dbms_job && make


###############################################################
#            Category: STAT - Statistics                     #
###############################################################

pg_profile:
	cd pg_profile && make

pg_tracing:
	cd pg_tracing && make

pg_stat_monitor:
	cd pg_stat_monitor && make

pg_store_plans:
	cd pg_store_plans && make

pg_datasentinel:
	cd pg_datasentinel && make

pgsentinel: # PGDG Included
	cd pgsentinel && make

pg_ash:
	cd pg_ash && make

pgfincore: # PGDG Included
	cd pgfincore && make

system_stats:
	cd system_stats && make

fbsql:
	cd fbsql && make

pg_meta:
	cd pg_meta && make

pg_mockable:
	cd pg_mockable && make

pgsqlmock:
	cd pgsqlmock && make

pgnodemx:
	cd pgnodemx && make

pg_sqlog:
	cd pg_sqlog && make

pgmeminfo:
	cd pgmeminfo && make

pg_stat_backtrace:
	cd pg_stat_backtrace && make

plpgsql_check:
	cd plpgsql_check && make

pg_relusage:
	cd pg_relusage && make

pg_track_optimizer:
	cd pg_track_optimizer && make

pg_pathcheck:
	cd pg_pathcheck && make

pagevis:
	cd pagevis && make

pg_isok:
	cd pg_isok && make


###############################################################
#            Category: SEC  - Security                       #
###############################################################

passwordcheck_cracklib:
	cd passwordcheck_cracklib && make

passwordpolicy:
	cd passwordpolicy && make

supautils:
	cd supautils && make

pgsodium:
	cd pgsodium && make

pg_vault:
	cd pg_vault && make

pg_tde:
	cd pg_tde && make

pg_auth_mon:
	cd pg_auth_mon && make

pgcryptokey:
	cd pgcryptokey && make

column_encrypt:
	cd column_encrypt && make

pg_jobmon:
	cd pg_jobmon && make

logerrors:
	cd logerrors && make

login_hook:
	cd login_hook && make

pg_auditor:
	cd pg_auditor && make

sslutils:
	cd sslutils && make

pg_noset:
	cd pg_noset && make

pg_strict:
	cd pg_strict && make


###############################################################
#            Category: SVC  - Service Packages               #
###############################################################

redis:
	cd redis && make


###############################################################
#            Category: FDW  - FDW                            #
###############################################################

pgspider_ext:
	cd pgspider_ext && make

sqlite_fdw:
	cd sqlite_fdw && make

pgbouncer_fdw:
	cd pgbouncer_fdw && make

odbc_fdw:
	cd odbc_fdw && make

hdfs_fdw:
	cd hdfs_fdw && make

jdbc_fdw:
	cd jdbc_fdw && make

redis_fdw:
	cd redis_fdw && make

mongo_fdw:
	cd mongo_fdw && make

pg_redis_pubsub:
	cd pg_redis_pubsub && make

kafka_fdw:
	cd kafka_fdw && make

libfq:
	cd libfq && make
zlog:
	cd zlog && make
polarstore:
	cd polarstore && make
graphblas:
	cd graphblas && make
lagraph:
	cd lagraph && make
onesparse:
	cd onesparse && make
pdu:
	cd pdu && make
pgdog:
	cd pgdog && make
firebird_fdw:
	cd firebird_fdw && make

aws_s3:
	cd aws_s3 && make

log_fdw:
	cd log_fdw && make

etcd_fdw:
	cd etcd_fdw && make

nominatim_fdw:
	cd nominatim_fdw && make


###############################################################
#            Category: SIM  - Similarity                     #
###############################################################

documentdb:
	cd documentdb && make

postgresbson:
	cd postgresbson && make

pgtt:
	cd pgtt && make

session_variable:
	cd session_variable && make

pg_variables:
	cd pg_variables && make

pg_statement_rollback:
	cd pg_statement_rollback && make

plpgsql_wrap:
	cd plpgsql_wrap && make

spat:
	cd spat && make


###############################################################
#            Category: EXP  - Experimental                   #
###############################################################

pg_trickle:
	cd pg_trickle && make

pg_stat_ch:
	cd pg_stat_ch && make

fsm_core:
	cd fsm_core && make

pg_command_fw:
	cd pg_command_fw && make

pg_dispatch:
	cd pg_dispatch && make

pg_fsql:
	cd pg_fsql && make

pg_liquid:
	cd pg_liquid && make

pg_regresql:
	cd pg_regresql && make

pg_slug_gen:
	cd pg_slug_gen && make

pgcalendar:
	cd pgcalendar && make

pgclone:
	cd pgclone && make

pgelog:
	cd pgelog && make

pglock:
	cd pglock && make

pgproto:
	cd pgproto && make

re2:
	cd re2 && make

rdf_fdw:
	cd rdf_fdw && make

ulak:
	cd ulak && make


###############################################################
#            Category: ETL  - ETL                            #
###############################################################

pglogical_ticker:
	cd pglogical_ticker && make

pg_failover_slots:
	cd pg_failover_slots && make

db_migrator:
	cd db_migrator && make

pgactive:
	cd pgactive && make

wal2mongo:
	cd wal2mongo && make

decoder_raw:
	cd decoder_raw && make

pg_bulkload:
	cd pg_bulkload && make

logical_ddl:
	cd logical_ddl && make

pg_fact_loader:
	cd pg_fact_loader && make



###############################################################
#                          Kernel                             #
###############################################################
openhalodb:
	cd openhalodb && make

ivorysql: ivorysql-18
ivorysql-18:
	cd ivorysql && make PG_MAJOR=18

orioledb: orioledb-18
oriole: orioledb
orioledb-16:
	cd orioledb && make orioledb-16
oriole_16: orioledb-16
orioledb-17:
	cd orioledb && make orioledb-17
oriole_17: orioledb-17
orioledb-18:
	cd orioledb && make orioledb-18
oriole_18: orioledb-18
orioledb-all:
	cd orioledb && make orioledb-all
oriole_all: orioledb-all
antlr4:
	cd antlr4_runtime413 && make

babelfish: babelfish-17
babelfish-18:
	cd babelfish && make PG_MAJOR=18 PG_VERSION=18.3 BBF_VERSION=6.0.0
babelfish-17:
	cd babelfish && make PG_MAJOR=17 PG_VERSION=17.7 BBF_VERSION=5.4.0
cloudberry:
	cd cloudberry && make
cloudberry-backup:
	cd cloudberry-backup && make
cloudberry-pxf:
	cd cloudberry-pxf && make
polardb:
	cd polardb && make
agensgraph:
	cd agensgraph && make

pgedge: pgedge-18
pgedge-15:
	cd pgedge && make PG_MAJOR=15
pgedge-16:
	cd pgedge && make PG_MAJOR=16
pgedge-17:
	cd pgedge && make PG_MAJOR=17
pgedge-18:
	cd pgedge && make PG_MAJOR=18

###############################################################
#                        1. Building                          #
###############################################################
haproxy:
	cd haproxy && make

# noext install
deps:
	sudo dpkg -i ~/libduckdb_*.deb
	sudo dpkg -i ~/libfq_*.deb
	sudo dpkg -i ~/zlog_*.deb
	sudo dpkg -i ~/polarstore_*.deb
	sudo dpkg -i ~/libgraphblas10_*.deb ~/libgraphblas-dev_*.deb
	sudo dpkg -i ~/liblagraph1_*.deb ~/liblagraphx1_*.deb ~/liblagraph-dev_*.deb
	sudo dpkg -i ~/scws_*.deb

collect:
	mkdir -p /tmp/deb
	cp -r ~/*.deb /tmp/deb/


.PHONY: deps collect haproxy \
	block_copy_command timescaledb_toolkit pg_later pg_polyline pg_tzf vchord pgvectorscale pgvector pg_vectorize pg_summarize pg_tiktoken pg_tiktoken_c pgml pg_search pg_when pg_bestmatch vchord_bm25 pg_tokenizer pg_mooncake pg_parquet pg_graphql pg_jsonschema pg_kazsearch pg_typescript pg_cardano pg_rrf plprql pglite_fusion pg_smtp_client pgmqtt pg_render pg_idkit pgx_ulid pg_base58 pg_convert pgdd pg_explain_ui pg_session_jwt pg_oidc_validator_rust pg_oidc_validator pg_anon pgsmcrypto wrappers pggraph pgrdf jsonschema \
	timescaledb pg_timeseries pg_bikram_sambat cron_utils temporal_tables emaj table_version pg_task pg_background pg_partman \
	geoip pg_geohash pghydro \
	smlar pg4ml \
	hunspell pgroonga pg_bigm pg_biscuit scws zhparser pg_cjk_parser pg_jieba pg_textsearch pg_fts \
	citus hydra storage_engine datasketches pg_duckdb pg_ducklake pg_lake duckdb_fdw pg_fkpart pg_kpart pg_clickhouse pg_orca \
	age pg_ttl_index index_advisor pg_plan_filter imgsmlr pg_ivm provsql fbsql pg_durable pgmnemo pg_projection pg_stl pg_sorted_heap pg_incremental pgmq pgmb omnigres pg_ai_query \
	plxslt pg_tle plv8 pljs plx \
	pgpdf md5hash pg_country pg_xenophile pg_currency pgcollection pguint pg_uint128 pg_text_semver hashtypes pg_duration pg_uri pg_emailaddr pg_acl timestamp9 chkpass \
	pg_gzip pg_http pg_bzip pg_zstd pg_net pg_curl pgjq pg_retry pgjwt pg_html5_email_address pg_utl_smtp url_encode pgsql_tweaks pg_extra_time pgqr pg_protobuf pg_envvar floatfile external_file pg_byteamagic pg_readme ddl_historization data_historization pg_schedoc pg_hashlib pg_xxhash shacrypt cryptint pg_ecdsa pgsparql \
	pg_uuidv7 pg_uuid_v8 permuteseq pg_hashids sequential_uuids topn quantile lower_quantile count_distinct omnisketch ddsketch vasco pgxicor pg_weighted_statistics floatvec aggs_for_vecs aggs_for_arrays parray_gin pg_accumulator pg_arraymath pg_math pg_random pg_base36 pg_base62 pg_financial argm faker dbt2 \
	pg_rewrite pg_query_rewrite pgdisablelogerror pg_cooldown pg_ddlx pg_readonly pg_permissions pg_upless pgcozy pg_orphaned pg_crash pg_cheat_funcs pg_fio pg_qos pg_savior safeupdate pg_drop_events pg_dbms_lock pg_dbms_errlog pg_dbms_metadata pg_dbms_job \
	pg_profile pg_tracing pg_stat_monitor pg_store_plans pg_datasentinel pgsentinel pg_ash pgfincore system_stats pg_meta pgsqlmock pgnodemx pg_sqlog pgmeminfo plpgsql_check pg_relusage pg_track_optimizer pg_pathcheck pagevis pg_isok \
	passwordcheck_cracklib passwordpolicy supautils pgsodium pg_vault pg_tde pg_auth_mon pgcryptokey column_encrypt pg_jobmon logerrors login_hook pg_auditor sslutils pg_noset pg_strict \
	redis \
	pgspider_ext sqlite_fdw pgbouncer_fdw odbc_fdw hdfs_fdw jdbc_fdw redis_fdw mongo_fdw pg_redis_pubsub kafka_fdw libfq zlog polarstore graphblas lagraph onesparse pdu pgdog firebird_fdw aws_s3 log_fdw etcd_fdw nominatim_fdw \
	documentdb postgresbson pgtt session_variable pg_variables pg_statement_rollback plpgsql_wrap spat pg_trickle pg_stat_ch fsm_core pg_command_fw pg_dispatch pg_fsql pg_liquid pg_regresql pg_slug_gen pgcalendar pgclone pgelog pglock pgproto re2 rdf_fdw ulak \
	pg_failover_slots db_migrator pgactive wal2mongo decoder_raw pg_bulkload logical_ddl pg_fact_loader \
	pglinter pg_enigma pg_typeid pg_pinyin pg_eviltransform \
	openhalodb ivorysql ivorysql-18 oriole oriole_16 oriole_17 oriole_18 oriole_all orioledb orioledb-16 orioledb-17 orioledb-18 orioledb-all antlr4 babelfish babelfish-17 babelfish-18 cloudberry cloudberry-backup cloudberry-pxf polardb agensgraph inchi \
	pgedge-15 pgedge-16 pgedge-17 pgedge-18
