.TH VALKEY-SENTINEL 1 "March 20, 2009"
.SH NAME
valkey-sentinel \- Valkey high availability monitor
.SH SYNOPSIS
.B valkey-sentinel
.RI configfile
.SH DESCRIPTION
Valkey is a key-value database. It is similar to memcached but the dataset is
not volatile and other datatypes (such as lists and sets) are natively
supported.
.PP
.SH OPTIONS
.IP "configfile"
Read options from specified configuration file.
.SH NOTES
On Debian GNU/Linux systems, \fBvalkey-sentinel\fP can be managed with the
\fBvalkey-sentinel.service\fP systemd unit. It uses
\fB/etc/valkey/sentinel.conf\fP by default.
.SH AUTHOR
\fBvalkey-sentinel\fP was written by Salvatore Sanfilippo.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
