#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if ! getent group postgres >/dev/null; then
        addgroup --system --gid 543 postgres
    fi

    if ! getent passwd postgres >/dev/null; then
        adduser --system --uid 543 --home /var/lib/postgresql --shell /bin/bash \
            --gecos "PostgreSQL Server" --ingroup postgres postgres
    fi

    install -d -m 0755 -o postgres -g postgres /var/lib/pgedge
    install -d -m 0700 -o postgres -g postgres /var/lib/pgedge/18
    install -d -m 0700 -o postgres -g postgres /var/lib/pgedge/18/main

    ldconfig
fi

exit 0
