#!/bin/sh
# Post-installation script for OpenHaloDB

set -e  # Exit immediately if a command exits with a non-zero status.

# Create postgres user/group if they don't exist
if [ "$1" = "configure" ]; then
    getent group postgres >/dev/null 2>&1 || \
        addgroup --system --gid 543 postgres 2>/dev/null || addgroup --system postgres
    getent passwd postgres >/dev/null 2>&1 || \
        adduser --system --uid 543 --home /var/lib/pgsql --shell /bin/bash \
            --gecos "PostgreSQL Server" --ingroup postgres postgres 2>/dev/null || \
        adduser --system --home /var/lib/pgsql --shell /bin/bash \
            --gecos "PostgreSQL Server" --ingroup postgres postgres

    # Update the dynamic linker run-time bindings
    ldconfig
fi

exit 0
