#!/bin/sh
set -eu

for version in $(cat debian/pgversions); do
	pg_virtualenv -v "$version" -t psql -X -v ON_ERROR_STOP=1 <<'SQL'
CREATE EXTENSION dbt2;
CREATE TABLE district (d_w_id integer, d_id integer, d_next_o_id integer);
CREATE TABLE order_line (ol_w_id integer, ol_d_id integer, ol_o_id integer, ol_i_id integer);
CREATE TABLE stock (s_w_id integer, s_i_id integer, s_quantity integer);
INSERT INTO district VALUES (1, 1, 21);
INSERT INTO order_line VALUES (1, 1, 1, 10);
INSERT INTO stock VALUES (1, 10, 5);
SELECT stock_level(1, 1, 10) = 1;
SQL
done
