#!/bin/sh
set -eu

for version in $(cat debian/pgversions); do
	pg_virtualenv -v "$version" -t psql -X -v ON_ERROR_STOP=1 <<'SQL'
CREATE EXTENSION pg_dbms_lock CASCADE;
SELECT count(*) = 2
  FROM pg_extension
 WHERE extname IN ('pg_background', 'pg_dbms_lock');
CALL dbms_lock.allocate_unique('autopkgtest_lock', NULL);
SQL
	pg_virtualenv -v "$version" -t \
		make PG_CONFIG="/usr/lib/postgresql/$version/bin/pg_config" installcheck
done
