#!/bin/sh
set -eu

for version in $(cat debian/pgversions); do
	pg_virtualenv -v "$version" -t psql -X -v ON_ERROR_STOP=1 <<'SQL'
CREATE EXTENSION pgbouncer_fdw CASCADE;
SELECT extversion = '1.4.0' FROM pg_extension WHERE extname = 'pgbouncer_fdw';
SELECT count(*) > 0 FROM pg_catalog.pg_views WHERE viewname LIKE 'pgbouncer_%';
SELECT count(*) > 0 FROM pg_catalog.pg_proc WHERE proname LIKE 'pgbouncer_%';
SQL
done
