#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if ! getent group postgres >/dev/null; then
        addgroup --system postgres
    fi

    if ! getent passwd postgres >/dev/null; then
        adduser --system --home /var/lib/pgsql --shell /bin/bash \
        --gecos "PostgreSQL Server" --ingroup postgres postgres
    fi

    ldconfig
fi

exit 0

